baseurl = "http://blog.burntsushi.net/"
languageCode = "en-us"
title = "Andrew Gallant's Blog"

[params]
author = "Andrew Gallant"
google_analytics_id = "UA-5095052-2"
description = "I blog mostly about my own programming projects."
