baseURL = "https://burntsushi.net/"
locale = "en-us"
title = "Andrew Gallant's Blog"
pygmentsUseClasses = true
pygmentsUseClassic = false
ignoreLogs = ["warning-goldmark-raw-html"]
disableKinds = ["taxonomy", "term", "section"]

[params.author]
name = "Andrew Gallant"
email = "jamslam@gmail.com"
