#!/usr/bin/env python2

from __future__ import absolute_import, division, print_function

import argparse
import os
import os.path as path
import re


CARGO_TOML = '''
[package]
name = "{post_name}"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
'''

RE_RUST_CODE = re.compile(r'^{{< code-rust "(?P<name>[^"]+)" >}}'
                          r'(?P<code>.+?)'
                          r'{{< /code-rust >}}',
                          re.DOTALL | re.MULTILINE)

if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('post')
    args = p.parse_args()

    post_name = path.splitext(path.basename(args.post))[0]
    post = open(args.post).read().decode('utf-8')
    code_dir = path.join('code', post_name)

    if not os.access(code_dir, os.R_OK):
        os.mkdir(code_dir)
        os.mkdir(path.join(code_dir, 'src'))
        os.mkdir(path.join(code_dir, 'src', 'bin'))
        print('target', file=open(path.join(code_dir, '.gitignore'), 'w+'))
        print(CARGO_TOML.format(post_name=post_name),
              file=open(path.join(code_dir, 'Cargo.toml'), 'w+'))
    for m in RE_RUST_CODE.finditer(post):
        src_path = path.join(code_dir, 'src', 'bin',
                             u'%s.rs' % m.group('name'))
        print(m.group('code').encode('utf-8'), file=open(src_path, 'w+'))
