#!/usr/bin/env python2

import os.path
import sys

import cmdlib as cmd

if len(sys.argv) <= 1:
    cmd.eprint('No file arguments found.')
    cmd.exit(1)

for f in sorted(sys.argv[1:]):
    title = open(f).readlines()[1].strip(' #\n')
    print os.path.basename(f), '::', title

